---
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/cnalabs/sample-helm-chart.git
  password: <Git Access Token>
  username: slabs-sec
